"""
confidence.py: Confidence scoring and transparency label generation.
 
it combines signal scores into a calibrated confidence score using
length-aware weighting, then maps to one of three label variants.
"""
 
 
# ── Confidence Scoring ─────────────────────────────────────────────────────────
 
def combine_scores(
    llm_score: float,
    stylo_score: float,
    word_count: int,
    perp_score: float | None = None,
) -> float:
    """
    Combine signal scores into a single calibrated AI-probability score.
 
    Length-aware weighting: stylometrics and perplexity proxy become more
    reliable on longer text, so their weights increase with word count.
    LLM signal is reliable at all lengths.
 
    Then applies a bias correction that nudges borderline scores toward
    "human" — reflecting the design decision that false positives
    (labeling human work as AI) are worse than false negatives.
 
    Args:
        llm_score:   float 0–1, higher = more AI-likely (Signal 1)
        stylo_score: float 0–1, higher = more AI-like structure (Signal 2)
        word_count:  number of words in the submitted text
        perp_score:  float 0–1 or None; higher = more predictable (Signal 3, optional)
 
    Returns:
        combined_score: float 0–1, higher = more likely AI-generated
    """
    use_perp = perp_score is not None
 
    # Length-aware weights
    if not use_perp:
        if word_count < 100:
            w = {"llm": 0.80, "stylo": 0.20}
        elif word_count < 200:
            w = {"llm": 0.65, "stylo": 0.35}
        else:
            w = {"llm": 0.50, "stylo": 0.50}
        raw = llm_score * w["llm"] + stylo_score * w["stylo"]
    else:
        if word_count < 100:
            w = {"llm": 0.70, "stylo": 0.15, "perp": 0.15}
        elif word_count < 200:
            w = {"llm": 0.55, "stylo": 0.25, "perp": 0.20}
        else:
            w = {"llm": 0.40, "stylo": 0.35, "perp": 0.25}
        raw = (
            llm_score   * w["llm"]
            + stylo_score * w["stylo"]
            + perp_score  * w["perp"]
        )
 
    # Bias correction: nudge borderline scores toward human
    # Only applies in the 0.45–0.60 band; max correction is -0.05
    if 0.45 <= raw <= 0.60:
        distance_from_center = abs(raw - 0.525)
        correction = 0.05 * (1.0 - distance_from_center / 0.075)
        raw = raw - max(0.0, correction)
 
    return round(max(0.0, min(1.0, raw)), 4)
 
 
# ── Attribution Label ──────────────────────────────────────────────────────────
 
def attribution_from_score(score: float) -> str:
    """Map combined score to attribution string."""
    if score >= 0.75:
        return "likely_ai"
    elif score >= 0.45:
        return "uncertain"
    else:
        return "likely_human"
 
 
# ── Transparency Label ─────────────────────────────────────────────────────────
 
def generate_label(combined_score: float) -> dict:
    """
    Generate the transparency label shown to platform readers.
 
    Returns a dict with:
        variant:    "high_confidence_ai" | "uncertain" | "high_confidence_human"
        text:       the exact label string to display
        score_pct:  human-readable score percentage
    """
    if combined_score >= 0.75:
        score_pct = round(combined_score * 100)
        variant = "high_confidence_ai"
        text = (
            f"⚠️ AI-Generated Content\n\n"
            f"Our system found strong indicators that this content was likely generated "
            f"by AI (confidence: {score_pct}%). This label reflects automated analysis "
            f"and may not be fully accurate. If you are the creator and believe this is "
            f"incorrect, you can submit an appeal."
        )
 
    elif combined_score >= 0.45:
        score_pct = round(combined_score * 100)
        variant = "uncertain"
        text = (
            f"🔍 Authorship Uncertain\n\n"
            f"Our system could not confidently determine whether this content was written "
            f"by a human or generated by AI (confidence: {score_pct}%). It will be treated "
            f"as unverified. Creators can submit an appeal to provide additional context."
        )
 
    else:
        # Invert for human-facing display: show human-confidence percentage
        score_pct = round((1.0 - combined_score) * 100)
        variant = "high_confidence_human"
        text = (
            f"✅ Likely Human-Written\n\n"
            f"Our system found no strong indicators of AI generation in this content "
            f"(confidence: {score_pct}% human). This is an automated assessment, not a guarantee."
        )
 
    return {
        "variant": variant,
        "text": text,
        "score_pct": score_pct,
    }
 
