"""
signal_llm.py — Signal 1: LLM-based classification via Groq.

Sends text to llama-3.3-70b-versatile and asks for a structured
assessment of whether it reads as AI-generated or human-written.
Returns a float 0.0–1.0 (higher = more likely AI-generated).
"""

import json
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
 
_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client


SYSTEM_PROMPT = """You are an AI authorship detection expert. Your task is to analyze a piece of writing and assess the probability that it was generated by an AI rather than written by a human.

Respond ONLY with a valid JSON object in this exact format — no markdown, no explanation, no preamble:
{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}

Where ai_probability is:
- Close to 1.0 if the text strongly reads as AI-generated (uniform rhythm, over-hedging, comprehensive but shallow, suspiciously smooth transitions)
- Close to 0.0 if the text strongly reads as human-written (irregular, personal, idiomatic, emotionally variable)
- Around 0.5 if genuinely uncertain

Be conservative — only give high scores (>0.75) when there are strong, specific indicators of AI generation."""


def score_llm(text: str) -> tuple[float, str]:
    """
    Classify text using the Groq LLM.

    Returns:
        (ai_probability: float, reasoning: str)
        ai_probability is 0.0–1.0, higher = more likely AI-generated.
    """
    client = _get_client()

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.1,  # Low temperature for consistent, calibrated outputs
            max_tokens=150,
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        probability = float(parsed["ai_probability"])
        reasoning = parsed.get("reasoning", "")

        # Clamp to valid range
        probability = max(0.0, min(1.0, probability))
        return probability, reasoning

    except (json.JSONDecodeError, KeyError, ValueError) as e:
        # If parsing fails, return a neutral uncertain score
        return 0.5, f"Parse error: {e}"
    except Exception as e:
        # Network or API error — return neutral
        return 0.5, f"API error: {e}"